services:
  gozargah-node:
    image: ghcr.io/m03ed/gozargah-node:dev
    restart: always
    network_mode: host

    environment:
      SERVICE_PORT: 62050
      SERVICE_PROTOCOL: "grpc"

      SSL_CERT_FILE: "/var/lib/gozargah-node/certs/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/gozargah-node/certs/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/gozargah-node/certs/ssl_client_cert.pem"

      GENERATED_CONFIG_PATH: "/var/lib/gozargah-node/generated"

    volumes:
      - /var/lib/gozargah-node:/var/lib/gozargah-node
